### ISSUE TITLE
Invalid syntax with python 3.5

### ISSUE THREAD

**Issue by fbartels** [yitsushi/doku#1]
Hi,

I am trying to install doku on a system running Ubuntu 16.04. Installation via pip succeeds, but afterwards running doku fails with the following:

```
$ doku
Traceback (most recent call last):
  File "/home/fbartels/.local/bin/doku", line 7, in <module>
    from doku.main import cli
  File "/home/fbartels/.local/lib/python2.7/site-packages/doku/main.py", line 7, in <module>
    from textwrap import indent
ImportError: cannot import name indent
```

**Comment by yitsushi** [comment]
I'm not sure how could you even install it with py27, it's marked on pypi with python3 [maybe there is a way to tell pypi it's not for py27]. So it does not work with py27.

In py27 there is no `textwrap.indent`.

I have no plans to support python 2.7, and good to mention it's EoL from January 1st, 2020.

**Comment by yitsushi** [comment]
I'm closing this because of the reasons above.

**Comment by fbartels** [comment]
yes, not supporting python2 makes absolute sense. Maybe python3.5 is too old as well?

```
$ doku
Traceback (most recent call last):
  File "/home/fbartels/.local/bin/doku", line 7, in <module>
    from doku.main import cli
  File "/home/fbartels/.local/lib/python3.5/site-packages/doku/main.py", line 9, in <module>
    from doku.context import Context
  File "/home/fbartels/.local/lib/python3.5/site-packages/doku/context.py", line 12
    client: Client
          ^
SyntaxError: invalid syntax
```

seems I should finally find some time to update that system to 18.04. :-D

**Comment by yitsushi** [comment]
hah. I did not know there is a huge difference in syntax between 3.5 and 3.7  :O

**Comment by yitsushi** [comment]
After digging deeper and deeper, I found two relevant PEPs:

[PEP 484 -- Type Hints](https://www.python.org/dev/peps/pep-0484/)
[PEP 526 -- Syntax for Variable Annotations](https://www.python.org/dev/peps/pep-0526/)

Based these PEPs, it's clear, py35 introduced type hinting, BUT only for function and type hinting for variables was introduced later in py36. [TIL :)]

Just finished my work on some tests and soon I'll remove type hinting from variables and will work with py35 too ;)

[option2: or I just make it clear it works only 3.6+]

**Comment by yitsushi** [comment]
TIL2: `f-strings` is also 3.6+ :O https://docs.python.org/3.6/whatsnew/3.6.html#whatsnew36-pep498

and with py35 everything is broken like: `AttributeError: 'PosixPath' object has no attribute 'startswith'`

I think I'll make it clear in the README it works with python3.6+ only. Sorry.

**Comment by yitsushi** [comment]
https://github.com/yitsushi/doku/commit/31575913ffdd5ca424342bdcc246efca3e2c7752#diff-88b99bb28683bd5b7e3a204826ead112R13
